# fly.toml app configuration file generated for test-bps9tq on 2026-05-15T17:40:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-bps9tq'
primary_region = 'sjc'

[build]

[[mounts]]
  source = 'cgroup'
  destination = '/sys/fs/cgroup'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
